# What Is Behind Changes in London’s Housing Affordability?
## Dataset selection

Source: Office for National Statistics (ONS), House price to
workplace-based earnings ratio, 2025 release.

I chose this dataset to explore how housing affordability differs
between London boroughs and how it has changed over time.

I will use sheet 5c, which contains median house-price-to-earnings
ratios by local authority.

A higher ratio means homes are less affordable relative to earnings.
Workplace-based earnings refer to people working in an area,
who may live elsewhere.

Main question: How did house prices and workplace earnings relate
to changes in London’s housing affordability between 2015 and 2025,
particularly since 2021?

I will analyse affordability ratios alongside median house prices
and median annual workplace-based earnings.

In [2]:
import pandas as pd

file_path = "aff1ratioofhousepricetoworkplacebasedearnings.xlsx"

df = pd.read_excel(
    file_path,
    sheet_name="5c",
    header=1
)

df.head()

,Country/Region code,Country/Region name,Local authority code,Local authority name,1997,1998,1999,2000,2001,2002,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,5-Year Average
0,E12000001,North East,E06000001,Hartlepool,2.64,2.74,2.85,3.02,2.75,2.9,...,4.8,4.82,5.00,4.63,4.94,4.65,4.73,4.59,4.8,4.74
1,E12000001,North East,E06000002,Middlesbrough,2.83,2.74,2.89,2.73,2.58,2.47,...,4.88,5.28,5.15,5,5.42,4.95,4.74,4.8,4.51,4.88
2,E12000001,North East,E06000003,Redcar and Cleveland,2.34,2.45,2.12,2.21,2.39,2.69,...,5.11,5.11,5.03,5.15,5.84,5.67,5.2,5.38,4.68,5.35
3,E12000001,North East,E06000004,Stockton-on-Tees,2.97,2.93,3.05,3.06,3.07,3.53,...,5.64,5.5,5.06,5.01,5.56,5.22,5.73,5.58,4.78,5.37
4,E12000001,North East,E06000005,Darlington,3.04,3.46,3.14,3.24,3.19,3.18,...,5.37,5.34,5.04,5.35,5.53,5.27,5.45,4.8,5.26,5.26

## Initial Data Exploration

Before cleaning, I will inspect the dataset's size, column names,
data types and final rows to understand its structure.

In [3]:
# Number of rows and columns
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

# Column names
print(df.columns.tolist())

Rows: 318
Columns: 34
['Country/Region code', 'Country/Region name', 'Local authority code', 'Local authority name', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025', '5-Year Average']

In [4]:
# Data types and non-missing counts
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 318 entries, 0 to 317
Data columns (total 34 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Country/Region code   318 non-null    str
 1   Country/Region name   318 non-null    str
 2   Local authority code  318 non-null    str
 3   Local authority name  318 non-null    str
 4   1997                  318 non-null    object
 5   1998                  318 non-null    object
 6   1999                  318 non-null    object
 7   2000                  318 non-null    object
 8   2001                  318 non-null    object
 9   2002                  318 non-null    object
 10  2003                  318 non-null    object
 11  2004                  318 non-null    object
 12  2005                  318 non-null    object
 13  2006                  318 non-null    object
 14  2007                  318 non-null    object
 15  2008                  318 non-null    object
 16  2009                  318 non-null    float64
 17  2010                  318 non-null    object
 18  2011                  318 non-null    object
 19  2012                  318 non-null    object
 20  2013                  318 non-null    object
 21  2014                  318 non-null    object
 22  2015                  318 non-null    object
 23  2016                  318 non-null    object
 24  2017                  318 non-null    object
 25  2018                  318 non-null    object
 26  2019                  318 non-null    float64
 27  2020                  318 non-null    object
 28  2021                  318 non-null    object
 29  2022                  318 non-null    object
 30  2023                  318 non-null    object
 31  2024                  318 non-null    object
 32  2025                  318 non-null    object
 33  5-Year Average        318 non-null    object
dtypes: float64(2), object(28), str(4)
memory usage: 84.6+ KB

In [5]:
# Check the final rows for notes or other non-data content
df.tail()

,Country/Region code,Country/Region name,Local authority code,Local authority name,1997,1998,1999,2000,2001,2002,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,5-Year Average
313,W92000004,Wales,W06000020,Torfaen,2.46,2.63,2.69,2.85,2.72,3.05,...,4.85,5.31,5.41,5.49,5.82,5.59,5.42,5.02,5.55,5.48
314,W92000004,Wales,W06000021,Monmouthshire,4.15,4.72,4.64,5.31,5.97,6.97,...,8.42,8.66,8.69,8.59,10.25,9.96,9.41,8.57,7.98,9.23
315,W92000004,Wales,W06000022,Newport,2.87,2.67,2.9,3.15,3.25,3.77,...,5.99,6.08,6.18,6.31,7.35,6.9,7.46,6.88,6.28,6.97
316,W92000004,Wales,W06000023,Powys,3.68,3.71,3.91,4.38,4.03,4.66,...,7.46,7.51,6.90,6.31,8.02,8.21,7.91,7.34,7.86,7.87
317,W92000004,Wales,W06000024,Merthyr Tydfil,1.92,2.09,2.27,2.36,2.17,2.28,...,4.14,3.74,4.09,4.61,4.94,4.87,4.84,4.9,4.57,4.82

## Data Quality Checks

I will check for duplicate rows and unavailable values before cleaning.
The ONS metadata defines [x] as no data available.

The analysis focuses on London, with wider regional comparisons.
I will check the wider dataset before creating the London subset.

In [6]:
years = [str(year) for year in range(2015, 2026)]

print("Duplicate rows:", df.duplicated().sum())

print("\nUnavailable values by year:")
print(df[years].eq("[x]").sum())

print("\nTotal unavailable values:")
print(df[years].eq("[x]").sum().sum())

Duplicate rows: 0

Unavailable values by year:
2015    1
2016    1
2017    1
2018    1
2019    0
2020    1
2021    1
2022    1
2023    1
2024    1
2025    1
dtype: int64

Total unavailable values:
10

In [7]:
# Show areas with unavailable values during 2015–2025
missing_rows = df[years].eq("[x]").any(axis=1)

df.loc[
    missing_rows,
    ["Country/Region name", "Local authority name"] + years
]

,Country/Region name,Local authority name,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
277,South West,Isles of Scilly,[x],[x],[x],[x],16.96,[x],[x],[x],[x],[x],[x]

## Data Cleaning

No duplicate rows were found, so none were removed.

There are 10 unavailable values, marked [x], all belonging to
the Isles of Scilly. Its 2019 ratio is available.

I will convert [x] to missing values and annual ratios to numeric
types. I will not fill missing ratios because there is insufficient
evidence to estimate them reliably.

I will retain area identifiers and years 2015–2025, excluding
earlier years and the five-year average to match the analysis scope.
The original DataFrame will remain unchanged.

In [8]:
# Keep area details and the selected years
area_columns = [
    "Country/Region code",
    "Country/Region name",
    "Local authority code",
    "Local authority name"
]

clean_df = df[area_columns + years].copy()

# Recognise unavailable values, then convert ratios to numbers
clean_df[years] = clean_df[years].replace("[x]", float("nan"))
clean_df[years] = clean_df[years].apply(pd.to_numeric, errors="raise")

# Check the result
print("Shape:", clean_df.shape)
print("Missing values:", clean_df[years].isna().sum().sum())

clean_df[years].dtypes

Shape: (318, 15)
Missing values: 10

2015    float64
2016    float64
2017    float64
2018    float64
2019    float64
2020    float64
2021    float64
2022    float64
2023    float64
2024    float64
2025    float64
dtype: object

### Reshaping the data

I will convert the separate year columns into a single year column
and a single affordability_ratio column.

This makes it easier to group, compare and plot values over time.
Missing values will remain missing.

In [9]:
long_df = clean_df.melt(
    id_vars=area_columns,
    value_vars=years,
    var_name="year",
    value_name="affordability_ratio"
)

long_df["year"] = long_df["year"].astype(int)

# Create the London subset
london_df = long_df[
    long_df["Country/Region name"] == "London"
].copy()

print("Full dataset:", long_df.shape)
print("London dataset:", london_df.shape)
print(
    "London missing ratios:",
    london_df["affordability_ratio"].isna().sum()
)

london_df.head()

Full dataset: (3498, 6)
London dataset: (363, 6)
London missing ratios: 0

,Country/Region code,Country/Region name,Local authority code,Local authority name,year,affordability_ratio
172,E12000007,London,E09000001,City of London,2015,15.25
173,E12000007,London,E09000002,Barking and Dagenham,2015,7.12
174,E12000007,London,E09000003,Barnet,2015,14.24
175,E12000007,London,E09000004,Bexley,2015,9.14
176,E12000007,London,E09000005,Brent,2015,13.34

## Exploring House Prices and Earnings

To understand changes in affordability, I will also examine
sheet 5a (median house prices) and sheet 5b (median annual
workplace-based earnings) from the same ONS workbook.

I will inspect these sheets before cleaning and combining them
with the affordability ratios.

In [10]:
# Load the additional sheets without changing existing data
prices_df = pd.read_excel(file_path, sheet_name="5a", header=1)
earnings_df = pd.read_excel(file_path, sheet_name="5b", header=1)

print("House prices:", prices_df.shape)
print("Earnings:", earnings_df.shape)

print("\nHouse-price columns:")
print(prices_df.columns.tolist())

print("\nEarnings columns:")
print(earnings_df.columns.tolist())

House prices: (318, 33)
Earnings: (318, 33)

House-price columns:
['Country/Region code', 'Country/Region name', 'Local authority code', 'Local authority name', 'Year ending Sep 1997', 'Year ending Sep 1998', 'Year ending Sep 1999', 'Year ending Sep 2000', 'Year ending Sep 2001', 'Year ending Sep 2002', 'Year ending Sep 2003', 'Year ending Sep 2004', 'Year ending Sep 2005', 'Year ending Sep 2006', 'Year ending Sep 2007', 'Year ending Sep 2008', 'Year ending Sep 2009', 'Year ending Sep 2010', 'Year ending Sep 2011', 'Year ending Sep 2012', 'Year ending Sep 2013', 'Year ending Sep 2014', 'Year ending Sep 2015', 'Year ending Sep 2016', 'Year ending Sep 2017', 'Year ending Sep 2018', 'Year ending Sep 2019', 'Year ending Sep 2020', 'Year ending Sep 2021', 'Year ending Sep 2022', 'Year ending Sep 2023', 'Year ending Sep 2024', 'Year ending Sep 2025']

Earnings columns:
['Country/Region code', 'Country/Region name', 'Local authority code', 'Local authority name', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']

In [11]:
# Work on copies so the original imports stay unchanged
prices_clean = prices_df.copy()
earnings_clean = earnings_df.copy()

# Standardise column headings
prices_clean.columns = (
    prices_clean.columns.astype(str)
    .str.replace("Year ending Sep ", "", regex=False)
    .str.strip()
)

earnings_clean.columns = (
    earnings_clean.columns.astype(str).str.strip()
)

# Keep area identifiers and 2015–2025
prices_clean = prices_clean[area_columns + years].copy()
earnings_clean = earnings_clean[area_columns + years].copy()

# Check data quality before converting values
for name, data in [
    ("House prices", prices_clean),
    ("Earnings", earnings_clean)
]:
    print(f"\n{name}")
    print("Duplicate rows:", data.duplicated().sum())
    print("Blank annual values:", data[years].isna().sum().sum())
    print("[x] markers:", data[years].eq("[x]").sum().sum())

House prices
Duplicate rows: 0
Blank annual values: 0
[x] markers: 0

Earnings
Duplicate rows: 0
Blank annual values: 0
[x] markers: 10

### Cleaning and combining prices and earnings

No duplicate rows were found in either selected table.
House prices contain no missing values, while earnings contain
10 unavailable values marked [x].

I will convert these markers to missing values without estimating
replacements, and convert prices and earnings to numeric types.

I will reshape both tables and join them to the ratios using
local authority code and year. Each join must be one-to-one
to prevent accidental duplication.

In [12]:
# Convert unavailable markers and numeric values
for data in [prices_clean, earnings_clean]:
    data[years] = data[years].replace("[x]", float("nan"))
    data[years] = data[years].apply(pd.to_numeric, errors="raise")

# Reshape house prices
prices_long = prices_clean.melt(
    id_vars=area_columns,
    value_vars=years,
    var_name="year",
    value_name="median_house_price"
)

# Reshape earnings
earnings_long = earnings_clean.melt(
    id_vars=area_columns,
    value_vars=years,
    var_name="year",
    value_name="median_annual_earnings"
)

prices_long["year"] = prices_long["year"].astype(int)
earnings_long["year"] = earnings_long["year"].astype(int)

# Combine using area code and year
join_keys = ["Local authority code", "year"]

analysis_df = long_df.merge(
    prices_long[join_keys + ["median_house_price"]],
    on=join_keys,
    how="left",
    validate="one_to_one"
).merge(
    earnings_long[join_keys + ["median_annual_earnings"]],
    on=join_keys,
    how="left",
    validate="one_to_one"
)

# Keep the London subset in a new variable
london_analysis = analysis_df[
    analysis_df["Country/Region name"] == "London"
].copy()

print("Combined dataset:", analysis_df.shape)
print("London dataset:", london_analysis.shape)

print("\nMissing values:")
print(analysis_df[
    ["affordability_ratio", "median_house_price", "median_annual_earnings"]
].isna().sum())

london_analysis.head()

Combined dataset: (3498, 8)
London dataset: (363, 8)

Missing values:
affordability_ratio       10
median_house_price         0
median_annual_earnings    10
dtype: int64

,Country/Region code,Country/Region name,Local authority code,Local authority name,year,affordability_ratio,median_house_price,median_annual_earnings
172,E12000007,London,E09000001,City of London,2015,15.25,823750,54034.0
173,E12000007,London,E09000002,Barking and Dagenham,2015,7.12,235000,33018.0
174,E12000007,London,E09000003,Barnet,2015,14.24,440000,30900.0
175,E12000007,London,E09000004,Bexley,2015,9.14,271000,29664.0
176,E12000007,London,E09000005,Brent,2015,13.34,400000,29987.0

In [13]:
calculated_ratio = (
    analysis_df["median_house_price"]
    / analysis_df["median_annual_earnings"]
)

difference = (
    calculated_ratio - analysis_df["affordability_ratio"]
).abs()

print("Largest ratio difference:", difference.max())
print(
    "Duplicate area-year records:",
    analysis_df.duplicated(["Local authority code", "year"]).sum()
)

Largest ratio difference: 0.005000000000000782
Duplicate area-year records: 0